### ISSUE TITLE
joinRooms all together?

### ISSUE THREAD

**Issue by dcsan** [dcsan/gitterbot#105]
according to chat with gitter.im folks, we can join multiple rooms at once
this will severly lower the number of API requests being made.

currently the app even in local dev mode seems to be loading ALL the bonfire rooms (80rooms?)
the API limit is 100req/minute and I've been seeing timeouts/API rate exceeded errors recently.

**Comment by dcsan** [comment]
after stop/restaring the app 2,3 times:

```
GBot.currentUser> failed [Error: 429 {"error":"API rate limit exceeded"}]
    at /Users/dc/dev/fcc/gitterbot/nap/lib/bot/GBot.js:33:19
    at _rejected (/Users/dc/dev/fcc/gitterbot/nap/node_modules/node-gitter/node_modules/q/q.js:797:24)
    at /Users/dc/dev/fcc/gitterbot/nap/node_modules/node-gitter/node_modules/q/q.js:823:30
    at Promise.when (/Users/dc/dev/fcc/gitterbot/nap/node_modules/node-gitter/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/Users/dc/dev/fcc/gitterbot/nap/node_modules/node-gitter/node_modules/q/q.js:741:41)
    at /Users/dc/dev/fcc/gitterbot/nap/node_modules/node-gitter/node_modules/q/q.js:557:44
    at flush (/Users/dc/dev/fcc/gitterbot/nap/node_modules/node-gitter/node_modules/q/q.js:108:17)
```

**Comment by dcsan** [comment]
> @dcsan Another possibility is adding the ability to join multiple rooms in a single request. You are using this resource endpoint for joining correct? https://developer.gitter.im/docs/rooms-resource#join-a-room

although that doc doesn't seem like we can join multiple rooms at once:
https://developer.gitter.im/docs/rooms-resource#join-a-room

```
Parameters
uri: Required URI of the room you would like to join.
Try it from the CLI:

$ curl -X POST -i -H "Content-Type: application/json" -H "Accept: application/json" -H "Authorization: Bearer 45b74dd48914a8b5f284635819aeb8047411bba9" "https://api.gitter.im/v1/rooms" -d '{"uri": "gitterhq/sandbox"}'
```

**Comment by dcsan** [comment]
cc @MadLittleMods can you clarify if we can join multiple rooms at once?

**Comment by dcsan** [comment]
update: this is requires a possible API change at their end.

**Comment by MadLittleMods** [comment]
@dcsan This does require an API change on our end which requires considerable thought on our part to make sure we get it right. We still have not decided on whether we will implement but will probably make a definite decision on Monday when another team member returns.

I am curious what all goes on on startup/initialization/bootstrap. I know that you join ~40 rooms which is 40 requests and scan the room list for any one to ones but I think that is 1 request. I can only count 41(I assume the bonfire rooms are included in that room count).

[`GBot.js` `init` source](https://github.com/dcsan/gitterbot/blob/f918142a7c09d274b96c3d5e96a88d0f19f43e12/nap/lib/bot/GBot.js#L22)

**Comment by dcsan** [comment]
I think the issue is around joining lots of DM rooms, where the bot has been messaged by people directly. as the app gets used, this list will grow to a large number. 
https://github.com/dcsan/gitterbot/blob/f918142a7c09d274b96c3d5e96a88d0f19f43e12/nap/lib/bot/GBot.js#L327

looking at this:
> var rooms = new realtimeClient.RoomCollection([], { client: client, listen: true });

So we can use one call to "bulk listen" to all rooms that are sending events for this user? That seems like what we need. 

rooms.on('add remove reset change', function(model) {
  console.log(rooms.toJSON());
});

so then we can also listen to `new` rooms being added. I am hoping that is the event that gets sent when out bot would get sent a DM? ie a new room would be getting created, and you get "auto added" to this.
