### ISSUE TITLE
more resilient API calls

### ISSUE THREAD

**Issue by dcsan** [dcsan/gitterbot#129]
when FCC API is down we currently fail hard:

wrap a try/catch at least around this...

```

  68 passing (3s)
  2 failing

  1) GitterHelper should find a room by name:
     Uncaught SyntaxError: Unexpected token <
      at Object.parse (native)
      at IncomingMessage.<anonymous> (lib/utils/HttpWrap.js:44:33)
      at _stream_readable.js:908:16

  2) HttpWrap should load user info:
     Uncaught SyntaxError: Unexpected token <
      at Object.parse (native)
      at IncomingMessage.<anonymous> (lib/utils/HttpWrap.js:44:33)
      at _stream_readable.js:908:16



<html>
^
SyntaxError: Unexpected token <
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/Users/dc/dev/fcc/gitterbot/nap/lib/utils/HttpWrap.js:44:33)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

```

**Comment by dcsan** [comment]
fixed for now in rel-010
