### ISSUE TITLE
crash on startup?

### ISSUE THREAD

**Issue by dcsan** [dcsan/gitterbot#160]
```
bot-0 (err): GBot hasAlreadyJoined: /camperbot/bonfire-title-case-a-sentence
bot-0 (err): GBot hasAlreadyJoined: /camperbot/bonfire-seek-and-destroy
bot-0 (err): /home/freecodecamp/www/gitterbot/nap/lib/utils/Utils.js:156
bot-0 (err):         path = path.replace("?", "%3F");  // not URL encoded
bot-0 (err):                    ^
bot-0 (err): TypeError: Cannot read property 'replace' of undefined
bot-0 (err):     at Object.Utils.linkify (/home/freecodecamp/www/gitterbot/nap/lib/utils/Utils.js:156:20)
bot-0 (err):     at Object.commands.wiki (/home/freecodecamp/www/gitterbot/nap/lib/bot/cmds/wiki.js:68:26)
bot-0 (err):     at Object.GBot.findAnyReply (/home/freecodecamp/www/gitterbot/nap/lib/bot/GBot.js:125:48)
bot-0 (err):     at Object.GBot.handleReply (/home/freecodecamp/www/gitterbot/nap/lib/bot/GBot.js:80:27)
bot-0 (err):     at null.<anonymous> (/home/freecodecamp/www/gitterbot/nap/lib/bot/GBot.js:73:18)
bot-0 (err):     at emit (/home/freecodecamp/www/gitterbot/nap/node_modules/node-gitter/node_modules/eventemitter3/index.js:72:35)
bot-0 (err):     at null.<anonymous> (/home/freecodecamp/www/gitterbot/nap/node_modules/node-gitter/lib/rooms.js:84:12)
bot-0 (err):     at EventEmitter.emit (/home/freecodecamp/www/gitterbot/nap/node_modules/node-gitter/node_modules/eventemitter3/index.js:72:35)
bot-0 (err):     at /home/freecodecamp/www/gitterbot/nap/node_modules/node-gitter/lib/faye.js:54:13
bot-0 (err):     at Object.handler (/home/freecodecamp/www/gitterbot/nap/node_modules/node-gitter/node_modules/gitter-faye/javascript/mixins/publisher.js:13:41)
bot-0 (err): WARN> AppConfig AppConfig.init serverEnv: prod
bot-0 (err): connect.multipart() will be removed in connect 3.0
bot-0 (err): visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
bot-0 (err): connect.limit() will be removed in connect 3.0
```

**Comment by dcsan** [comment]
maybe bonfire links? links are broken/don't exist for that bonfire?

**Comment by dcsan** [comment]
```
bot-0 GBot> FreeCodeCamp/FreeCodeCamp @TimCoding: 
bot-0 GBot>  in| thank you @shadowprogram !
bot-0 GBot> out|  > timcoding sends brownie points to @shadowprogram :sparkles: :thumbsup: :sparkles: 
bot-0 GitterHelper non 200 response from { uri: 'https://gitter.im/api/v1/rooms',
  headers: 
   { 'Content-Type': 'application/json',
     Accept: 'application/json',
     Authorization: 'Bearer b8726fc238b88377618ca1bf096a3556e5745276' } }
bot-0 GitterHelper body {"error":"API rate limit exceeded"}
bot-0 can't find rooms with roomUri FreeCodeCamp/FreeCodeCamp 
bot-0     at /home/freecodecamp/www/gitterbot/nap/lib/gitter/GitterHelper.js:110:27
    at Request._callback (/home/freecodecamp/www/gitterbot/nap/lib/gitter/GitterHelper.js:54:24)
    at Request.self.callback (/home/freecodecamp/www/gitterbot/nap/node_modules/request/request.js:129:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/freecodecamp/www/gitterbot/nap/node_modules/request/request.js:873:14)
    at emitOne (events.js:82:20)
bot-0 GitterHelper non 200 response from { uri: 'https://gitter.im/api/v1/rooms',
  headers: 
   { 'Content-Type': 'application/json',
     Accept: 'application/json',
     Authorization: 'Bearer b8726fc238b88377618ca1bf096a3556e5745276' } }
bot-0 GitterHelper body {"error":"API rate limit exceeded"}
bot-0 can't find rooms with roomUri FreeCodeCamp/FreeCodeCamp 
bot-0     at /home/freecodecamp/www/gitterbot/nap/lib/gitter/GitterHelper.js:110:27
    at Request._callback (/home/freecodecamp/www/gitterbot/nap/lib/gitter/GitterHelper.js:54:24)
    at Request.self.callback (/home/freecodecamp/www/gitterbot/nap/node_modules/request/request.js:129:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/freecodecamp/www/gitterbot/nap/node_modules/request/request.js:873:14)
    at emitOne (events.js:82:20)
bot-0 GBot> FreeCodeCamp/FreeCodeCamp @Crysicia: 
bot-0 GBot>  in| XD
```

**Comment by abhisekp** [comment]
@dcsan is it because of the new camperbot room addition code?

**Comment by abhisekp** [comment]
@dcsan is it possible to get all rooms from gitter for freecodecamp organisation and join all those rooms?

**Comment by dcsan** [comment]
no i havent deployed that yet.

i think it maybe a bonfire with bad links related to MDN

could you put a guard around that `path ` call?

```js
    if (!path)  { 
         Utils.error("path", "tried to take question marks out of a non-existent path");
         return; 
    } 
```

or something like that?

bot-0 (err):         path = path.replace("?", "%3F");  // not URL encoded

**Comment by dcsan** [comment]
`!path` will trap undefined and null, correct?

**Comment by dcsan** [comment]
i prefer coffeescripts `unless path` ...

**Comment by abhisekp** [comment]
why does it say `bot-0 can't find rooms with roomUri FreeCodeCamp/FreeCodeCamp `

**Comment by dcsan** [comment]
OK Pushed a fix for this.

other error is down to the "joiing too many rooms" gitter issue
