### ISSUE TITLE
rooms page on web part of site

### ISSUE THREAD

**Issue by dcsan** [dcsan/gitterbot#58]
```
bot-0 TypeError: /home/freecodecamp/www/gitterbot/nap/views/rooms.jade:21
    19|               a.btn.btn-lg.btn-success(href="/go?room=#{room.name}&who=#{who}") #{room.name} &nbsp;
    20|             .col-md-8
  > 21|               - each topic in room.topics
    22|                 a.btn.btn-default(href="/go?topic=#{topic}&who=#{who}") #{topic}
    23|                 &nbsp;
    24|                 span /go?topic=#{topic}&who=#{who}

Cannot read property 'length' of undefined
    at eval (eval at <anonymous> (/home/freecodecamp/www/gitterbot/nap/node_modules/jade/lib/jade.js:152:8), <anonymous>:313:31)
    at eval (eval at <anonymous> (/home/freecodecamp/www/gitterbot/nap/node_modules/jade/lib/jade.js:152:8), <anonymous>:380:4)
    at eval (eval at <anonymous> (/home/freecodecamp/www/gitterbot/nap/node_modules/jade/lib/jade.js:152:8), <anonymous>:521:4)
    at /home/freecodecamp/www/gitterbot/nap/node_modules/jade/lib/jade.js:153:35
    at Object.exports.render (/home/freecodecamp/www/gitterbot/nap/node_modules/jade/lib/jade.js:197:10)
    at Object.exports.renderFile (/home/freecodecamp/www/gitterbot/nap/node_modules/jade/lib/jade.js:233:18)
    at View.exports.renderFile [as engine] (/home/freecodecamp/www/gitterbot/nap/node_modules/jade/lib/jade.js:218:21)
    at View.render (/home/freecodecamp/www/gitterbot/nap/node_modules/express/lib/view.js:76:8)
    at Function.app.render (/home/freecodecamp/www/gitterbot/nap/node_modules/express/lib/application.js:504:10)
    at ServerResponse.res.render (/home/freecodecamp/www/gitterbot/nap/node_modules/express/lib/response.js:798:7)
```

**Comment by dcsan** [comment]
/rooms/ 

route is broken
